### ISSUE TITLE
Is it ready and can I do something

### ISSUE THREAD

**Issue by Yaqf** [ZhcnPanda/android_device_xiaomi_cezanne#1]
I see the repo is active, is it working?

---

似乎是中文开发者，我也用中文吧。

我看到仓库一直处于活跃开发中，它可以正常构建使用吗？

如果可以，我可以帮忙添加 GitHub Action CI/CD。不过我对 Android 开发并不了解，可能需要一些帮助

**Comment by SaKongA** [comment]
这个device tree还不是很完善，建议去看一下这个repo，里面是k30ultra最完善的dt

https://github.com/coolscode

**Comment by Yaqf** [comment]
Thanks
